profiling: fix exception when generating single subplot
This commit fixes the following error:

```
14:36:27 ERROR PipelineMonProfiler: profiler subject-50159-<unknown> has failed
Traceback (most recent call last):
  File "/.../pytest/.venv/lib/python3.11/site-packages/lbr_testsuite/profiling/profiler.py", line 171, in run_safe
    self.run()
  File "/.../pytest/.venv/lib/python3.11/site-packages/lbr_testsuite/profiling/pipeline.py", line 307, in run
    self._plot_stage_latencies(df, context.get_stages())
  File "/.../pytest/.venv/lib/python3.11/site-packages/lbr_testsuite/profiling/pipeline.py", line 236, in _plot_stage_latencies
    for name, ax in zip(proc_names, axes):
                    ^^^^^^^^^^^^^^^^^^^^^
TypeError: 'Axes' object is not iterable
```

The error was caused by attempting to generate subplots with only one
row and one column (i.e. a single plot). In that case,
matplotlib.subplots() method only outputs a single Axes object instead
of a list of Axes objects.

This commit fixes the issue by wrapping the object into a list first.

Fixes: 6e90b283 ("profiling: introduce extracted package")